- name: Adding Host to Group AAP Controller
  hosts: localhost
  tasks:
    - name: Add host to group
      group:
        name: "{{ group | default('eos') }}"
        description: ""
        # awx_inventory_name is provided at runtime when running from AAP
        inventory: "{{ awx_inventory_name }}"
        hosts:
          - "{{ gen_name }}.lab.test"