- name: Adding Host to Group AAP Controller
  hosts: localhost
  tasks:
    - name: Add host to group
      ansible.controller.group:
        name: "{{ group | default('eos') }}"
        description: ""
        controller_host: "rhel-9.lab.test"
        controller_oauthtoken: "{{ controller_token }}"
        # awx_inventory_name is provided at runtime when running from AAP
        inventory: "{{ awx_inventory_name }}"
        hosts:
          - "{{ gen_name }}.lab.test"
