---
- name: Create Backup of DB
  hosts: "{{ qa_host | default('all') }}"
  gather_facts: false
  # vars:
  #   mssql_login_user: "sa"
  #   mssql_login_password: ""
  #   mssql_host: "sql-qa-server-gns3.lab.test"
  #   mssql_port: 1433
  #   db: SampleDB

  tasks:
    - name: Create Backup
      community.general.mssql_script:
        login_user: "{{ mssql_login_user }}"
        login_password: "{{ mssql_login_password }}"
        login_host: "{{ qa_host }}"
        login_port: 1433
        db: "{{ db }}"
        script: |
          BACKUP DATABASE [{{ db }}] TO DISK = '/tmp/{{ db }}.bak'
      connection: local
      delegate_to: localhost
    
    - name: Add read permissions to file
      ansible.builtin.file:
        path: "/tmp/{{ db }}.bak"
        mode: '0644'
      become: true