---
- name: Configure SNMP
  hosts: "{{ gen_name | default('all') }}"
  gather_facts: false
  roles:
    - role: roles/networking-snmp
      snmp:
        host: "{{ snmp.host }}"
        community: "{{ snmp.community }}"
        community_string: "{{ snmp.community_string }}"