---
- name: Update Change ticket
  hosts: localhost

  tasks:  
    - name: Change change_request
      servicenow.itsm.change_request:
        state: assess
        close_notes: "{{ hostvars[inventory_hostname] | to_nice_yaml }}"
        assignment_group: "Hardware"
        number: "{{ change_request['record']['number'] }}"
