- name: Check when device is up
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Wait for the port to be up
      ansible.builtin.wait_for:
        port: "{{ port }}"
        host: "{{ survey_name }}"
        delay: 60  # Wait for 60 seconds before starting checks
        timeout: 300  # Timeout after 300 seconds (5 minutes)
        state: started  # Ensure the port is started
      delegate_to: localhost