---
interfaces:
  - name: GigabitEthernet1
    description: "MGMT connection"
    ipv4:
      - address: 192.168.0.53/24
    enabled: true

  - name: GigabitEthernet2
    description: "BGP Point-To-Point"
    ipv4:
      - address: 192.168.1.10/32
    speed: "1000"
    duplex: "full"
    enabled: false

  - name: GigabitEthernet3
    description: "UPLINK-SACR2001"
    speed: "auto"
    duplex: "auto"
    enabled: true