- name: Cisco Uplink Remediation - Troubleshooting
  hosts: all
  gather_facts: false

  tasks:
    - name: Format Incoming Interface
      ansible.builtin.set_fact:
        interface_num: "{{ interface | regex_search('\\d+') }}"

    - name: Find specific interface
      ansible.builtin.set_fact:
        matched_interface: "{{ item }}"
      loop: "{{ interfaces }}"
      when: item.name | regex_search('\\d+') == interface_num

    - name: Configure Uplink
      cisco.ios.ios_interfaces:
        config: 
          - "{{ matched_interface }}"
      