- name: Deploy EC2 instance using Ansible
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ survey_name }}"
        image_id: "ami-08012c0a9ee8e21c4"
        instance_type: "{{ survey_instance_type }}"
        region: us-east-1
        wait: true
        count: 1
        state: present
