---
- name: Troubleshoot BGP on Cisco Device
  hosts: "{{ survey_name | default('all') }}"
  gather_facts: no
  tasks:
    - name: Show BGP neighbors
      cisco.ios.ios_command:
        commands:
          - show ip bgp summary
      register: bgp_summary

    - name: Display BGP Neighbor Status
      debug:
        var: bgp_summary.stdout_lines