- name: Add Administrator group to manage system
  hosts: "{{ survey_name }}"
  gather_facts: false

  tasks:
    - name: Wait for port 22 to become available
      ansible.builtin.wait_for:
        port: 22
        host: '{{ survey_name }}'
        timeout: 600
    - name: Create admin group
      ansible.builtin.group:
        name: admin
        state: present

    - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: johnd
        comment: John Doe
        uid: 1040
        group: admin
    
    - name: Add the user 'jamesd' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: jamesd
        comment: James Dow
        uid: 1041
        group: admin

