---
- name: Ansible apt update all packages on Ubuntu/Debian
  hosts: "{{ survey_name }}"
  gather_facts: false
  tasks:
    - name: Wait for port 22 to become available
      ansible.builtin.wait_for:
        port: 22
        host: '{{ survey_name }}'
        timeout: 1500
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      ansible.builtin.apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600